### ISSUE TITLE
Had to add 'Logs' folder after building application

### ISSUE THREAD

**Issue by 1nnovat1on** [CyberPunkMetalHead/cryptocurrency-machine-learning-prediction-algo-trading#2]
added  ...\cryptocurrency-machine-learning-prediction-algo-trading\Logs\

**Comment by sleeyax** [comment]
You can make git keep the folder by creating an empty file at  `Logs\.gitkeep`. I don't have time to make a PR for this right now, maybe you can?

**Comment by zradishdp** [comment]
The program keeps making errors and won't run.
Does anybody have a problem?

**Comment by CyberPunkMetalHead** [comment]
Thanks, I will include this in a new PR

**Comment by 1nnovat1on** [comment]
@zradishdp what errors?
