### ISSUE TITLE
Prediction always the same

### ISSUE THREAD

**Issue by Squaldo** [CyberPunkMetalHead/cryptocurrency-machine-learning-prediction-algo-trading#5]
I can't get a prediction, it is always:

Prediction (67799,54) is smaller than the open (2273869000000) or current (2271533000000) price, skipping buy and awaiting new prediction.

Is this a BTC-Hourly.csv path issue perhaps?

**Comment by CyberPunkMetalHead** [comment]
Have you configured your binance keys etc? That open price is rather strange response.

Could you try re-training the model? It shouldn't need access to the csv unless you're looking to re-train it.

**Comment by Squaldo** [comment]
Yes the keys are configured, and the open and close prices seem to be accurate, but the prediction price seems strange don’t you think?
How do I re-train the model?

**Comment by Squaldo** [comment]
It was a regional issue, I’m in Europe ;) It is working now. Thx!

**Comment by CyberPunkMetalHead** [comment]
np!
